server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3002"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
      routes:
        - id: empleado-service
          uri: lb://empleado-service
          predicates:
            - Path=/empleado/**
        - id: planilla-service
          uri: lb://planilla-service
          predicates:
            - Path=/planilla/**
        - id: marca-service
          uri: lb://marca-service
          predicates:
            - Path=/marca/**
        - id: justificativo-service
          uri: lb://justificativo-service
          predicates:
            - Path=/justificativo/**
        - id: horasExtras-service
          uri: lb://horasExtras-service
          predicates:
            - Path=/horasExtras/**